/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as HorizontalLayoutRouteImport } from './routes/_horizontal-layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as HorizontalLayoutItem3RouteImport } from './routes/_horizontal-layout/item3'
import { Route as HorizontalLayoutItem2RouteImport } from './routes/_horizontal-layout/item2'
import { Route as HorizontalLayoutItem1RouteImport } from './routes/_horizontal-layout/item1'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const HorizontalLayoutRoute = HorizontalLayoutRouteImport.update({
  id: '/_horizontal-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const HorizontalLayoutItem3Route = HorizontalLayoutItem3RouteImport.update({
  id: '/item3',
  path: '/item3',
  getParentRoute: () => HorizontalLayoutRoute,
} as any)
const HorizontalLayoutItem2Route = HorizontalLayoutItem2RouteImport.update({
  id: '/item2',
  path: '/item2',
  getParentRoute: () => HorizontalLayoutRoute,
} as any)
const HorizontalLayoutItem1Route = HorizontalLayoutItem1RouteImport.update({
  id: '/item1',
  path: '/item1',
  getParentRoute: () => HorizontalLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/item1': typeof HorizontalLayoutItem1Route
  '/item2': typeof HorizontalLayoutItem2Route
  '/item3': typeof HorizontalLayoutItem3Route
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/item1': typeof HorizontalLayoutItem1Route
  '/item2': typeof HorizontalLayoutItem2Route
  '/item3': typeof HorizontalLayoutItem3Route
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_horizontal-layout': typeof HorizontalLayoutRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_horizontal-layout/item1': typeof HorizontalLayoutItem1Route
  '/_horizontal-layout/item2': typeof HorizontalLayoutItem2Route
  '/_horizontal-layout/item3': typeof HorizontalLayoutItem3Route
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/item1'
    | '/item2'
    | '/item3'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/item1'
    | '/item2'
    | '/item3'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_horizontal-layout'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_horizontal-layout/item1'
    | '/_horizontal-layout/item2'
    | '/_horizontal-layout/item3'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HorizontalLayoutRoute: typeof HorizontalLayoutRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_horizontal-layout': {
      id: '/_horizontal-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HorizontalLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_horizontal-layout/item3': {
      id: '/_horizontal-layout/item3'
      path: '/item3'
      fullPath: '/item3'
      preLoaderRoute: typeof HorizontalLayoutItem3RouteImport
      parentRoute: typeof HorizontalLayoutRoute
    }
    '/_horizontal-layout/item2': {
      id: '/_horizontal-layout/item2'
      path: '/item2'
      fullPath: '/item2'
      preLoaderRoute: typeof HorizontalLayoutItem2RouteImport
      parentRoute: typeof HorizontalLayoutRoute
    }
    '/_horizontal-layout/item1': {
      id: '/_horizontal-layout/item1'
      path: '/item1'
      fullPath: '/item1'
      preLoaderRoute: typeof HorizontalLayoutItem1RouteImport
      parentRoute: typeof HorizontalLayoutRoute
    }
  }
}

interface HorizontalLayoutRouteChildren {
  HorizontalLayoutItem1Route: typeof HorizontalLayoutItem1Route
  HorizontalLayoutItem2Route: typeof HorizontalLayoutItem2Route
  HorizontalLayoutItem3Route: typeof HorizontalLayoutItem3Route
}

const HorizontalLayoutRouteChildren: HorizontalLayoutRouteChildren = {
  HorizontalLayoutItem1Route: HorizontalLayoutItem1Route,
  HorizontalLayoutItem2Route: HorizontalLayoutItem2Route,
  HorizontalLayoutItem3Route: HorizontalLayoutItem3Route,
}

const HorizontalLayoutRouteWithChildren =
  HorizontalLayoutRoute._addFileChildren(HorizontalLayoutRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HorizontalLayoutRoute: HorizontalLayoutRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
