/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTable3RouteImport } from './routes/_layout/table3'
import { Route as LayoutTable2RouteImport } from './routes/_layout/table2'
import { Route as LayoutTable1RouteImport } from './routes/_layout/table1'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDemoRouteImport } from './routes/_layout/demo'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutTable3IndexRouteImport } from './routes/_layout/table3.index'
import { Route as LayoutTable2IndexRouteImport } from './routes/_layout/table2.index'
import { Route as LayoutTable1IndexRouteImport } from './routes/_layout/table1.index'
import { Route as LayoutTable3IdRouteImport } from './routes/_layout/table3.$id'
import { Route as LayoutTable2IdRouteImport } from './routes/_layout/table2.$id'
import { Route as LayoutTable1IdRouteImport } from './routes/_layout/table1.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTable3Route = LayoutTable3RouteImport.update({
  id: '/table3',
  path: '/table3',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTable2Route = LayoutTable2RouteImport.update({
  id: '/table2',
  path: '/table2',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTable1Route = LayoutTable1RouteImport.update({
  id: '/table1',
  path: '/table1',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDemoRoute = LayoutDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTable3IndexRoute = LayoutTable3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTable3Route,
} as any)
const LayoutTable2IndexRoute = LayoutTable2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTable2Route,
} as any)
const LayoutTable1IndexRoute = LayoutTable1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTable1Route,
} as any)
const LayoutTable3IdRoute = LayoutTable3IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutTable3Route,
} as any)
const LayoutTable2IdRoute = LayoutTable2IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutTable2Route,
} as any)
const LayoutTable1IdRoute = LayoutTable1IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutTable1Route,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/demo': typeof LayoutDemoRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/table1': typeof LayoutTable1RouteWithChildren
  '/table2': typeof LayoutTable2RouteWithChildren
  '/table3': typeof LayoutTable3RouteWithChildren
  '/': typeof LayoutIndexRoute
  '/table1/$id': typeof LayoutTable1IdRoute
  '/table2/$id': typeof LayoutTable2IdRoute
  '/table3/$id': typeof LayoutTable3IdRoute
  '/table1/': typeof LayoutTable1IndexRoute
  '/table2/': typeof LayoutTable2IndexRoute
  '/table3/': typeof LayoutTable3IndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/demo': typeof LayoutDemoRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/table1/$id': typeof LayoutTable1IdRoute
  '/table2/$id': typeof LayoutTable2IdRoute
  '/table3/$id': typeof LayoutTable3IdRoute
  '/table1': typeof LayoutTable1IndexRoute
  '/table2': typeof LayoutTable2IndexRoute
  '/table3': typeof LayoutTable3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/demo': typeof LayoutDemoRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/table1': typeof LayoutTable1RouteWithChildren
  '/_layout/table2': typeof LayoutTable2RouteWithChildren
  '/_layout/table3': typeof LayoutTable3RouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/table1/$id': typeof LayoutTable1IdRoute
  '/_layout/table2/$id': typeof LayoutTable2IdRoute
  '/_layout/table3/$id': typeof LayoutTable3IdRoute
  '/_layout/table1/': typeof LayoutTable1IndexRoute
  '/_layout/table2/': typeof LayoutTable2IndexRoute
  '/_layout/table3/': typeof LayoutTable3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/demo'
    | '/items'
    | '/settings'
    | '/table1'
    | '/table2'
    | '/table3'
    | '/'
    | '/table1/$id'
    | '/table2/$id'
    | '/table3/$id'
    | '/table1/'
    | '/table2/'
    | '/table3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/demo'
    | '/items'
    | '/settings'
    | '/'
    | '/table1/$id'
    | '/table2/$id'
    | '/table3/$id'
    | '/table1'
    | '/table2'
    | '/table3'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/demo'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/table1'
    | '/_layout/table2'
    | '/_layout/table3'
    | '/_layout/'
    | '/_layout/table1/$id'
    | '/_layout/table2/$id'
    | '/_layout/table3/$id'
    | '/_layout/table1/'
    | '/_layout/table2/'
    | '/_layout/table3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table3': {
      id: '/_layout/table3'
      path: '/table3'
      fullPath: '/table3'
      preLoaderRoute: typeof LayoutTable3RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table2': {
      id: '/_layout/table2'
      path: '/table2'
      fullPath: '/table2'
      preLoaderRoute: typeof LayoutTable2RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table1': {
      id: '/_layout/table1'
      path: '/table1'
      fullPath: '/table1'
      preLoaderRoute: typeof LayoutTable1RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/demo': {
      id: '/_layout/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof LayoutDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/table3/': {
      id: '/_layout/table3/'
      path: '/'
      fullPath: '/table3/'
      preLoaderRoute: typeof LayoutTable3IndexRouteImport
      parentRoute: typeof LayoutTable3Route
    }
    '/_layout/table2/': {
      id: '/_layout/table2/'
      path: '/'
      fullPath: '/table2/'
      preLoaderRoute: typeof LayoutTable2IndexRouteImport
      parentRoute: typeof LayoutTable2Route
    }
    '/_layout/table1/': {
      id: '/_layout/table1/'
      path: '/'
      fullPath: '/table1/'
      preLoaderRoute: typeof LayoutTable1IndexRouteImport
      parentRoute: typeof LayoutTable1Route
    }
    '/_layout/table3/$id': {
      id: '/_layout/table3/$id'
      path: '/$id'
      fullPath: '/table3/$id'
      preLoaderRoute: typeof LayoutTable3IdRouteImport
      parentRoute: typeof LayoutTable3Route
    }
    '/_layout/table2/$id': {
      id: '/_layout/table2/$id'
      path: '/$id'
      fullPath: '/table2/$id'
      preLoaderRoute: typeof LayoutTable2IdRouteImport
      parentRoute: typeof LayoutTable2Route
    }
    '/_layout/table1/$id': {
      id: '/_layout/table1/$id'
      path: '/$id'
      fullPath: '/table1/$id'
      preLoaderRoute: typeof LayoutTable1IdRouteImport
      parentRoute: typeof LayoutTable1Route
    }
  }
}

interface LayoutTable1RouteChildren {
  LayoutTable1IdRoute: typeof LayoutTable1IdRoute
  LayoutTable1IndexRoute: typeof LayoutTable1IndexRoute
}

const LayoutTable1RouteChildren: LayoutTable1RouteChildren = {
  LayoutTable1IdRoute: LayoutTable1IdRoute,
  LayoutTable1IndexRoute: LayoutTable1IndexRoute,
}

const LayoutTable1RouteWithChildren = LayoutTable1Route._addFileChildren(
  LayoutTable1RouteChildren,
)

interface LayoutTable2RouteChildren {
  LayoutTable2IdRoute: typeof LayoutTable2IdRoute
  LayoutTable2IndexRoute: typeof LayoutTable2IndexRoute
}

const LayoutTable2RouteChildren: LayoutTable2RouteChildren = {
  LayoutTable2IdRoute: LayoutTable2IdRoute,
  LayoutTable2IndexRoute: LayoutTable2IndexRoute,
}

const LayoutTable2RouteWithChildren = LayoutTable2Route._addFileChildren(
  LayoutTable2RouteChildren,
)

interface LayoutTable3RouteChildren {
  LayoutTable3IdRoute: typeof LayoutTable3IdRoute
  LayoutTable3IndexRoute: typeof LayoutTable3IndexRoute
}

const LayoutTable3RouteChildren: LayoutTable3RouteChildren = {
  LayoutTable3IdRoute: LayoutTable3IdRoute,
  LayoutTable3IndexRoute: LayoutTable3IndexRoute,
}

const LayoutTable3RouteWithChildren = LayoutTable3Route._addFileChildren(
  LayoutTable3RouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDemoRoute: typeof LayoutDemoRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTable1Route: typeof LayoutTable1RouteWithChildren
  LayoutTable2Route: typeof LayoutTable2RouteWithChildren
  LayoutTable3Route: typeof LayoutTable3RouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDemoRoute: LayoutDemoRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTable1Route: LayoutTable1RouteWithChildren,
  LayoutTable2Route: LayoutTable2RouteWithChildren,
  LayoutTable3Route: LayoutTable3RouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
